### ISSUE TITLE
Getting started docs?

### ISSUE THREAD

**Issue by mikepurvis** [ros-industrial/universal_robot#101]
I'm unsure if these exist and I just can't find them, or if they need to be created— either way, the ROS package pages on the wiki should contain (or link to) some basic getting started info, especially for the simulator. I started by adding some skeletal content (based on what I could figure out) to the following:

http://wiki.ros.org/ur_description
http://wiki.ros.org/ur5_moveit_config
http://wiki.ros.org/ur_gazebo

With the instructions I've currently placed on the gazebo page, I can get to gazebo arm, rviz visualization, and planning, but I can't get the gazebo arm to actually execute the plan. Is there a step I'm missing here? If so, it'd be great to have that page made complete.

**Comment by fmessmer** [comment]
@mikepurvis 
Thanks for setting up those pages!

There is a README here: 
https://github.com/ros-industrial/universal_robot/blob/hydro-devel/README.md
In that file, all the commands are given which are required to get started with both a real or a simulated UR5/UR10 respectively.

The reason why you cannot execute your motion plan in simulation is most likely because of the namespacing problem between topics and actions used with the real hardware and the simulation, i.e. the FollowJointTrajectory actions in simulation is provided under a different namespace as is configured in the moveit_config. This is also adressed in the README.

According to ROS-Industrial tutorials (http://wiki.ros.org/Industrial/Tutorials/Create_a_MoveIt_Pkg_for_an_Industrial_Robot#Plan_and_Execute_on_a_Real_Robot). There is a `urX_moveit_planning_execution.launch` file that you can use with `sim:=true` handling the remapping.

Hope that helps!

**Comment by mikepurvis** [comment]
Ah, terrific, thanks for the assistance. Failure to read the readme—duh.

I wonder if it would be best to avoid repetition, perhaps by either:
- Removing the wikipage content and supplying instead a link to the README and generic ROS-I tutorials.
- Removing the README content and instead simply including a link to the getting started info on the wiki.

Thoughts?

**Comment by shaun-edwards** [comment]
My preference is to populate the ROS wiki.  I've seen a lot of groups move their documentation to github wikis/readmes.  The wiki provides a great deal of context(i.e. versions, API docs, dependency listing, etc...), that is valuable.  Also, I'd prefer to keep all ROS documentation centrally located in order to avoid fragmentation.

**Comment by fmessmer** [comment]
The github README will significantly be improved once #131 and #132 are merged

**Comment by abubeck** [comment]
As updates have been done. I will close this.
