### ISSUE TITLE
Moveit planning execution launch files do not set controller_joint_names parameter

### ISSUE THREAD

**Issue by BrettHemes-3M** [ros-industrial/universal_robot#250]
Not sure if this is missing for a reason but the other robot packages in the ros-industrial set this parameter.  Fixed via PR #249

**Comment by gavanderhoorn** [comment]
The reason these packages don't set the `controller_joint_names` parameter is because they don't make use of the shared infrastructure provided by the `industrial_robot_client` nodes, hence they have no need for it.

Ultimately this is because the `universal_robot` stack is one of the oldest (if not the oldest: first commit (eaff5f37) was March 2012) in ROS-Industrial. It was created before any of the conventions of the other packages were set up.

**Comment by gavanderhoorn** [comment]
Closing as the associated PR was also closed.

Thanks @BrettHemes for reporting this :+1:
