### ISSUE TITLE
Moveit planning takes longer in Hydro vs. Groovy

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/universal_robot#55]
Switching to Hydro, the default planner doesn’t seem to work that well.  It takes much longer to come up with solutions if it does at all, where in Groovy this wasn’t an issue.  Perhaps the default constraints have changed from Groovy

**Comment by fmessmer** [comment]
Did you use the `limited` argument?
The urX_moveit_configs can be used with either normal or joint_limited version of urX respectively!
Simply use 
`roslaunch urX_moveit_config demo.launch limited:=true`
OR
`roslaunch urX_moveit_config move_group.launch limited:=true`

Otherwise, the moveit_configs are default configs, i.e. using the values the MoveIt! SetupAssistant suggests. One thing I saw is that the velocity and joint limits are different in hydro-devel.

**Comment by shaun-edwards** [comment]
This was before that fix was implemented.  It is more of a general observation that a Consortium member made.  I just wanted to capture it to remind us to check.  It could be that we solved this problem.  I've assigned it to myself to verify the bug still exists.

**Comment by shaun-edwards** [comment]
Upon talking to the user further, these problems seem to have been addressed.  Closing.
