### ISSUE TITLE
Driver won't tolerate being started before the arms are ready.

### ISSUE THREAD

**Issue by jeff-o** [ros-industrial/universal_robot#59]
If the driver launches before the arm is ready, it will crash.  It must be launched manually after the arm has been powered up and initialized.  This is inconvenient when integrating the arm onto a mobile platform that is controlled by a single power switch.

If the arm is not ready when the ROS master boots, the driver should instead sit idle until the arm is ready to begin accepting commands.  The driver could first ping the IP address of the arm at regular intervals, and once ping is successful attempt some sort of handshake.

**Comment by mikepurvis** [comment]
+1 to this. The naive version would be just wrapping the `TCPServer` setup in a try block and a loop:

https://github.com/ros-industrial/universal_robot/blob/c637563121e463ddaaf6ac3266c2ffdf3ad10ac1/ur_driver/src/ur_driver/driver.py#L948

A more enlightened implementation would wrap the whole driver so that certain classes of errors (eg, loss of comms with the arm) cause it to jump back to the initialization loop rather than crash.

**Comment by mikepurvis** [comment]
Ack, there's more to this than I realised. The first part is making the driver not crash when the robot is not yet powered on or finished booting up. That is resolved here:

https://github.com/mikepurvis/universal_robot/commit/fcb0a46fcc9fdc11e839276081f920388bb2d67d

However, the second bit which I'd failed to understand is that the driver _also_ crashes out if the arm has not completed its lengthy initialization and self-calibration routine. This requires a more in-depth look at the driver to resolve.

**Comment by mikepurvis** [comment]
In general, I'm finding that there are several pretty easy ways that the driver, the arm, or both can be gotten into a state where only a reboot (or manual actions via the teach pendant) is able to recover them:
- Arm is stopped via an estop.
- Arm is stopped via an over-force event.
- Attempting to connect to the arm before the calibration has completed.

**Comment by tnl-woi** [comment]
Hi guys,
I'm not sure if we're talking about the same problem, since I don't recognize that the driver "crashes", but when starting the driver too early (before the robot is completely started up), the driver hangs forever in the "Waiting to program" loop. In this case the driver must be killed and restarted.
Is this the problem you're referring to? If not, could you please elaborate?

I've been tempted to fix this problem myself a while ago, but was not sure if there are reasons to NOT automatically reconnect. Could this lead to safety or control problems? Because the Teach Pendant and the robot driver will be fighting over the control then ;-) For example, when manually controlling the robot using the TP, the driver connection will be lost. If the driver would automatically reconnect, I think this would disturb the manual control using the pendant, and none of the controllers will be able to control the robot successfully.
And more importantly, in case of an emergency stop I'm not sure if it's a good idea if the driver would reconnect automatically and allow control again. I think there must be some way of "manual" intervention (this could be a software call to clear the error, as long as it is an explicit request from the client).

I'm curious about your opinions on this.

Regards, Wouter.

**Comment by jeff-o** [comment]
Our setups tend to be a little unique, in that we don't actually have a pendant controller attached at all. There is a secret menu option of n which the teach pendant requirement can be disabled. There is also a way to cause the arm to automatically initialize itself on startup. 

Perhaps a good start would be to parameterize whether a teach pendant is connected, and whether auto-initialization is enabled. From there other driver behaviors can be controlled.

**Comment by gavanderhoorn** [comment]
`ur_driver` is deprecated and will not see any development any more.

If this is (still) an issue with any of the replacements, please open an issue on the appropriate repository (and please link to this one).

Closing this.
