### ISSUE TITLE
I/O-Interface for UR

### ISSUE THREAD

**Issue by fmessmer** [ros-industrial/universal_robot#79]
From the Mailinglist (https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/i5twnmpf2ws), I learned that there is another version of the universal_robot stack that is used for the ROS-I training (https://github.com/ros-industrial/industrial_training/tree/hydro/training/supplements/src/universal_robot).
The thread mentions that this version also provides services for setting and getting I/Os from the UR.

Two questions:
- Why is there a different repo? Would it be possible to combine them? Or at least sync them?
- How mature is the I/O interface? Should it be integrated into this repo as well?

Because I noticed that the I/O messages there got the same define value (https://github.com/ros-industrial/industrial_training/blob/hydro/training/supplements/src/universal_robot/ur_driver/src/ur_driver/driver.py#L43) as the TCP force message from here #77 and #78 
Also the location for defining services diverges!

**Comment by wcaarls** [comment]
When I originally forked the repo to add I/O (https://github.com/wcaarls/universal_robot) I just wanted to make something work quickly for our students at TU Delft to use. However, because I don't work with the robot myself I couldn't test it thoroughly and therefore didn't submit a patch to the original repository. Now I don't even have access to a UR5 any more, so it would be great if someone else could integrate it, making sure it's more in line with the other patches.

**Comment by abubeck** [comment]
@wcaarls : when you could send a pull request we can test it on our versions of UR5 and UR10.

**Comment by shaun-edwards** [comment]
All, the universal driver with IO support created by @wcaarls was experimental, but fulfilled an immediate need we had.  We found that the driver locks up when IO messages were sent before motion commands (I can give more detail if required).  By the nature of our tutorial, this issue did not present itself, so it was not an issue for us.  This is why we didn't roll the change into the official universal driver.

I'm all for adding this capability to the official driver.  From the discussion referenced by @ipa-fxm, Andy has improved/changed the code.  We should consider pulling his code, instead of @wcaarls.

**Comment by airplanesrule** [comment]
@shaun-edwards can you give more detail on the bug where the driver locks up? I have tried sending both I/O and movement commands to the ur5 without any issue (so far), but theres a pretty decent chance my version will have the same bug since it is coded in almost exactly the same way

**Comment by wcaarls** [comment]
@shaun-edwards @airplanesrule : I think it would be great to use Andy's code as a base, considering it supports more I/O methods and receives more active development.

**Comment by jrgnicho** [comment]
Adding onto @shaun-edwards  comments on the I/O lock up issue, what I observed is that if an I/O service request is sent first and then it is followed by a motion request, the behaviour is that the I/O call is handled correctly but it leaves the driver in a state where it fails to handle the motion request.  When the subsequent motion request reaches the driver the physical robot controller is reset and the arm must be calibrated again.  To test this theory, I purposely reversed the order of commands, motion first followed by I/O request.  In this case, no further occurrences of controller resets took place again and the ur driver worked as expected.

**Comment by fmessmer** [comment]
Could Andy (@airplanesrule ?) please send a PullRequest with his latest code, so that more people could look into it?

**Comment by fmessmer** [comment]
This discussion is related to #81 
Thanks for providing this PR

**Comment by fmessmer** [comment]
Initial IO-Support is available since #92 
However, #118 discusses some shortcomings and suggests a revision.

I'm closing this issue. Discussion should be continued in #118
